events {}

http {
    upstream app_backend {
        # Only ONE environment should be active at a time
        server blue:8081;
        #server green:8082;
    }

    server {
        listen 80;
        server_name _;

        location / {
            proxy_pass http://app_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
